### ISSUE TITLE
VisualScript access to action value

### ISSUE THREAD

**Issue by Gallilus** [Gallilus/VisualScriptCustomNodes#1]
https://github.com/godotengine/godot-visual-script/issues/7

**Comment by Gallilus** [comment]
![image](https://user-images.githubusercontent.com/20573784/131018178-60f035af-a36c-42e2-afd2-d27977811ac8.png)

**Comment by josterburg** [comment]
Sorry for late answer... Outlook thought github was spam...

This already looks quite like what I wanted. It even adds the concept of positive and negative action to VisualScript :smile: 
I would prefer a version like the bottom one but with "Action" attached before it. Of cause this will use much space but I believe it is important to see and know that this is an action-node.

**Comment by Gallilus** [comment]
It is in the latest update. So your able to test it. 
I went for the last one so it is not to big.
